# Generated by Django 5.2.8 on 2025-11-30 15:52

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Federation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('iso_code', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SkatingElement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('element_name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=20, unique=True)),
                ('discipline_type', models.CharField(choices=[('JUMP', 'Jump'), ('SPIN', 'Spin'), ('SPIN COMBINATION', 'Spin Combination'), ('STEP SEQUENCE', 'Step Sequence'), ('CHOREOGRAPHIC ELEMENT', 'Choreographic Element'), ('THROW JUMP', 'Throw Jump'), ('TWIST LIFT', 'Twist Lift'), ('PAIR SPIN', 'Pair Spin'), ('PAIR SPIN COMBINATION', 'Pair Spin Combination'), ('PAIR LIFT', 'Pair Lift'), ('DEATH SPIRAL', 'Death Spiral'), ('PAIR ELEMENT', 'Pair Element'), ('PATTERN DANCE', 'Pattern Dance'), ('PATTERN DANCE ELEMENT', 'Pattern Dance Element'), ('DANCE STEP', 'Dance Step'), ('DANCE SPIN', 'Dance Spin'), ('DANCE LIFT', 'Dance Lift'), ('DANCE TWIZZLE', 'Dance Twizzle'), ('DANCE STEP/TURN', 'Dance Step/Turn'), ('DANCE EDGE ELEMENT', 'Dance Edge Element'), ('CHOREOGRAPHIC', 'Choreographic'), ('SYNCHRO ARTISTIC', 'Synchro Artistic'), ('SYNCHRO CREATIVE', 'Synchro Creative'), ('SYNCHRO LIFT', 'Synchro Lift'), ('SYNCHRO INTERSECTION', 'Synchro Intersection'), ('SYNCHRO FORMATION', 'Synchro Formation'), ('SYNCHRO PIVOTING', 'Synchro Pivoting'), ('SYNCHRO SPIN', 'Synchro Spin'), ('SYNCHRO TWIZZLE', 'Synchro Twizzle'), ('SYNCHRO', 'Synchro Mixed'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('element_category', models.CharField(choices=[('SINGLES', 'Singles'), ('PAIRS', 'Pairs'), ('ICE_DANCE', 'Ice Dance'), ('SYNCHRO', 'Synchro')], default='SINGLES', max_length=20)),
            ],
            options={
                'ordering': ['element_category', 'discipline_type', 'element_name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(choices=[('COACH', 'Coach'), ('SKATER', 'Skater'), ('GUARDIAN', 'Guardian'), ('OBSERVER', 'Observer')], default='SKATER', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AthleteSeason',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('season', models.CharField(max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('primary_coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coached_seasons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('province_state', models.CharField(max_length=100)),
                ('country', models.CharField(default='CA', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_competitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('REGISTERED', 'Registered'), ('COMPLETED', 'Completed')], default='COMPLETED', max_length=20)),
                ('level', models.CharField(max_length=100)),
                ('placement', models.IntegerField(blank=True, null=True)),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('planned_base_value', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('segment_scores', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, null=True)),
                ('detailed_protocol', models.JSONField(blank=True, default=list)),
                ('detail_sheet', models.FileField(blank=True, null=True, upload_to='competitions/protocols/')),
                ('video_url', models.URLField(blank=True, help_text='Link to full event video', null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.competition')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-competition__start_date'],
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('COACH', 'Coach'), ('SKATER', 'Skater'), ('GUARDIAN', 'Guardian'), ('OBSERVER', 'Observer'), ('COLLABORATOR', 'Collaborator'), ('MANAGER', 'Team Manager'), ('ATHLETE', 'Athlete'), ('PARENT', 'Parent')], max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('token', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('season', models.CharField(max_length=50)),
                ('program_category', models.CharField(choices=[('Short Program', 'Short Program'), ('Free Skate', 'Free Skate'), ('Rhythm Dance', 'Rhythm Dance'), ('Free Dance', 'Free Dance'), ('Artistic', 'Artistic'), ('Other', 'Other')], default='Free Skate', max_length=50)),
                ('music_title', models.CharField(blank=True, max_length=255, null=True)),
                ('choreographer', models.CharField(blank=True, max_length=255, null=True)),
                ('music_file', models.FileField(blank=True, null=True, upload_to='programs/music/')),
                ('est_base_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('planned_elements', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramAsset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='programs/assets/')),
                ('asset_type', models.CharField(choices=[('COSTUME', 'Costume'), ('HAIR', 'Hair & Makeup'), ('DESIGN', 'Design/Sketch'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='api.program')),
            ],
        ),
        migrations.CreateModel(
            name='SessionLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session_date', models.DateField(default=datetime.date.today)),
                ('object_id', models.PositiveIntegerField()),
                ('energy_stamina', models.IntegerField(default=3, help_text='1-5 Rating')),
                ('session_rating', models.IntegerField(default=3, help_text='1-5 Star Rating')),
                ('sentiment_emoji', models.CharField(blank=True, max_length=10, null=True)),
                ('wellbeing_focus_check_in', models.JSONField(blank=True, default=list)),
                ('wellbeing_mental_focus_notes', models.TextField(blank=True, null=True)),
                ('coach_notes', models.TextField(blank=True, null=True)),
                ('skater_notes', models.TextField(blank=True, null=True)),
                ('attendance', models.JSONField(blank=True, default=list)),
                ('jump_focus', models.JSONField(blank=True, default=dict)),
                ('spin_focus', models.JSONField(blank=True, default=dict)),
                ('synchro_element_focus', models.JSONField(blank=True, default=dict)),
                ('athlete_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_logs', to='api.athleteseason')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_session_logs', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-session_date'],
            },
        ),
        migrations.CreateModel(
            name='Skater',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('is_active', models.BooleanField(default=True, help_text='If false, skater is archived.')),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('NON_BINARY', 'Non-Binary'), ('OTHER', 'Other')], max_length=10, null=True)),
                ('home_club', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('federation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.federation')),
                ('user_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skaters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='SinglesEntity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('current_level', models.CharField(blank=True, max_length=100, null=True)),
                ('federation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.federation')),
                ('skater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='singles_entities', to='api.skater')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('meeting_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('meeting_type', models.JSONField(blank=True, default=list)),
                ('participants', models.TextField(blank=True, null=True)),
                ('summary_notes', models.TextField(blank=True, null=True)),
                ('skaters', models.ManyToManyField(related_name='meetings', to='api.skater')),
            ],
            options={
                'ordering': ['-meeting_date'],
            },
        ),
        migrations.CreateModel(
            name='InjuryLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('injury_type', models.CharField(max_length=100)),
                ('body_area', models.JSONField(blank=True, default=list)),
                ('date_of_onset', models.DateField()),
                ('return_to_sport_date', models.DateField(blank=True, null=True)),
                ('severity', models.CharField(blank=True, max_length=50, null=True)),
                ('recovery_status', models.CharField(blank=True, max_length=100, null=True)),
                ('recovery_notes', models.TextField(blank=True, null=True)),
                ('skater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injury_logs', to='api.skater')),
            ],
            options={
                'ordering': ['-date_of_onset'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('object_id', models.PositiveIntegerField()),
                ('goal_type', models.CharField(blank=True, max_length=50, null=True)),
                ('goal_timeframe', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('smart_description', models.TextField(blank=True, null=True)),
                ('progress_notes', models.TextField(blank=True, null=True)),
                ('current_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REVISION', 'Needs Revision'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('coach_review_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_goals', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_goals', to=settings.AUTH_USER_MODEL)),
                ('assignee_skater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_goals', to='api.skater')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='athleteseason',
            name='skater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='athlete_seasons', to='api.skater'),
        ),
        migrations.CreateModel(
            name='AthleteProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skater_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('guardian_name', models.CharField(blank=True, max_length=255, null=True)),
                ('guardian_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('relevant_medical_notes', models.TextField(blank=True, help_text='Allergies, conditions, etc.', null=True)),
                ('skater', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='api.skater')),
            ],
        ),
        migrations.CreateModel(
            name='SkaterTest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('test_type', models.CharField(default='Skills', max_length=100)),
                ('test_name', models.CharField(max_length=255)),
                ('test_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('WITHDRAWN', 'Withdrawn')], default='PLANNED', max_length=20)),
                ('result', models.CharField(blank=True, choices=[('Pass', 'Pass'), ('Retry', 'Retry'), ('Honors', 'Pass with Honors')], max_length=50, null=True)),
                ('evaluator_notes', models.TextField(blank=True, null=True)),
                ('test_sheet', models.FileField(blank=True, null=True, upload_to='tests/sheets/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('skater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='api.skater')),
            ],
        ),
        migrations.CreateModel(
            name='SoloDanceEntity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('current_level', models.CharField(blank=True, max_length=100, null=True)),
                ('federation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.federation')),
                ('skater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solodance_entities', to='api.skater')),
            ],
        ),
        migrations.CreateModel(
            name='SynchroTeam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=255, unique=True)),
                ('level', models.CharField(max_length=100)),
                ('federation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.federation')),
                ('roster', models.ManyToManyField(blank=True, related_name='synchro_teams', to='api.skater')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=255)),
                ('discipline', models.CharField(choices=[('PAIRS', 'Pairs'), ('ICE_DANCE', 'Ice Dance')], max_length=10)),
                ('current_level', models.CharField(blank=True, max_length=100, null=True)),
                ('federation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.federation')),
                ('partner_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams_as_partner_a', to='api.skater')),
                ('partner_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams_as_partner_b', to='api.skater')),
            ],
        ),
        migrations.CreateModel(
            name='TeamTrip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('travel_segments', models.JSONField(blank=True, default=list)),
                ('guests', models.JSONField(blank=True, default=list)),
                ('hotel_info', models.TextField(blank=True, help_text='Hotel name, address, booking block', null=True)),
                ('ground_transport_notes', models.TextField(blank=True, help_text='Transport at destination (e.g. Shuttle bus to rink)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='api.competition')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('activity', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('TRAVEL', 'Travel'), ('ICE', 'On Ice'), ('OFF_ICE', 'Off Ice / Warmup'), ('MEAL', 'Meal'), ('MEETING', 'Meeting'), ('COMPETITION', 'Competition'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='api.teamtrip')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='HousingAssignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room_number', models.CharField(blank=True, max_length=50, null=True)),
                ('guest_occupants', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, null=True)),
                ('occupants', models.ManyToManyField(blank=True, related_name='trip_rooms', to='api.skater')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooming_list', to='api.teamtrip')),
            ],
        ),
        migrations.CreateModel(
            name='YearlyPlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField()),
                ('peak_type', models.CharField(choices=[('Single Peak', 'Single Peak'), ('Double Peak', 'Double Peak'), ('Triple Peak', 'Triple Peak'), ('Development', 'Development')], default='Single Peak', max_length=50)),
                ('primary_season_goal', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete_seasons', models.ManyToManyField(related_name='yearly_plans', to='api.athleteseason')),
                ('coach_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_plans', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Macrocycle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phase_title', models.CharField(max_length=100)),
                ('phase_start', models.DateField()),
                ('phase_end', models.DateField()),
                ('phase_focus', models.TextField(blank=True, null=True)),
                ('technical_focus', models.TextField(blank=True, null=True)),
                ('component_focus', models.TextField(blank=True, null=True)),
                ('physical_focus', models.TextField(blank=True, null=True)),
                ('mental_focus', models.TextField(blank=True, null=True)),
                ('yearly_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macrocycles', to='api.yearlyplan')),
            ],
            options={
                'ordering': ['phase_start'],
            },
        ),
        migrations.CreateModel(
            name='GapAnalysis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('elements_status', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'unique_together': {('content_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='PlanningEntityAccess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('access_level', models.CharField(choices=[('COACH', 'Coach'), ('GUARDIAN', 'Guardian'), ('OBSERVER', 'Observer')], max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'content_type', 'object_id', 'access_level')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyPlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('week_start', models.DateField()),
                ('theme', models.CharField(blank=True, max_length=255, null=True)),
                ('session_breakdown', models.JSONField(blank=True, default=dict)),
                ('athlete_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_plans', to='api.athleteseason')),
            ],
            options={
                'ordering': ['week_start'],
                'unique_together': {('athlete_season', 'week_start')},
            },
        ),
    ]
