# Generated by Django 5.2.8 on 2025-11-28 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='federation',
            name='flag_emoji',
        ),
        migrations.AddField(
            model_name='federation',
            name='iso_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
