# Generated by Django 5.2.8 on 2025-11-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearlyplan',
            name='title',
            field=models.CharField(blank=True, help_text="Custom name for this plan (e.g. 'Road to Gold')", max_length=100, null=True),
        ),
    ]
