# Generated by Django 5.2.8 on 2025-11-17 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skater',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('NON_BINARY', 'Non-Binary'), ('OTHER', 'Other')], max_length=10, null=True)),
                ('home_club', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skater_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='SinglesEntity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('current_level', models.CharField(blank=True, max_length=100, null=True)),
                ('federation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.federation')),
                ('skater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='singles_entities', to='api.skater')),
            ],
        ),
        migrations.CreateModel(
            name='SoloDanceEntity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('current_level', models.CharField(blank=True, max_length=100, null=True)),
                ('federation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.federation')),
                ('skater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solodance_entities', to='api.skater')),
            ],
        ),
        migrations.CreateModel(
            name='SynchroTeam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=255, unique=True)),
                ('level', models.CharField(max_length=100)),
                ('federation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.federation')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=255)),
                ('discipline', models.CharField(choices=[('PAIRS', 'Pairs'), ('ICE_DANCE', 'Ice Dance')], max_length=10)),
                ('current_level', models.CharField(blank=True, max_length=100, null=True)),
                ('federation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.federation')),
                ('partner_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams_as_partner_a', to='api.skater')),
                ('partner_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams_as_partner_b', to='api.skater')),
            ],
        ),
        migrations.CreateModel(
            name='PlanningEntityAccess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('access_level', models.CharField(choices=[('COACH', 'Coach'), ('GUARDIAN', 'Guardian'), ('OBSERVER', 'Observer')], max_length=10)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'content_type', 'object_id', 'access_level')},
            },
        ),
    ]
