# Generated by Django 5.2.8 on 2025-11-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_yearlyplan_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionlog',
            options={'ordering': ['-session_date', '-session_time']},
        ),
        migrations.AddField(
            model_name='sessionlog',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sessionlog',
            name='session_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionlog',
            name='session_type',
            field=models.CharField(choices=[('ON_ICE', 'On Ice'), ('OFF_ICE', 'Off Ice'), ('COMPETITION', 'Competition'), ('CLASS', 'Class / Dance'), ('OTHER', 'Other')], default='ON_ICE', max_length=20),
        ),
    ]
