# Generated by Django 5.2.8 on 2025-11-17 20:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_skater_singlesentity_solodanceentity_synchroteam_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteSeason',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('season', models.CharField(max_length=10)),
                ('primary_coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athlete_seasons_as_primary', to=settings.AUTH_USER_MODEL)),
                ('skater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_seasons', to='api.skater')),
            ],
            options={
                'ordering': ['skater__full_name', '-season'],
                'unique_together': {('skater', 'season')},
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('object_id', models.PositiveIntegerField()),
                ('goal_type', models.CharField(blank=True, max_length=50, null=True)),
                ('goal_timeframe', models.CharField(blank=True, max_length=50, null=True)),
                ('smart_description', models.TextField(blank=True, null=True)),
                ('progress_notes', models.TextField(blank=True, null=True)),
                ('current_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REVISION', 'Needs Revision'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('coach_review_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee_skater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_goals', to='api.skater')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='InjuryLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('injury_type', models.CharField(max_length=100)),
                ('body_area', models.JSONField(blank=True, default=list)),
                ('date_of_onset', models.DateField()),
                ('return_to_sport_date', models.DateField(blank=True, null=True)),
                ('severity', models.CharField(blank=True, max_length=50, null=True)),
                ('recovery_status', models.CharField(blank=True, max_length=100, null=True)),
                ('recovery_notes', models.TextField(blank=True, null=True)),
                ('skater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injury_logs', to='api.skater')),
            ],
            options={
                'ordering': ['-date_of_onset'],
            },
        ),
        migrations.CreateModel(
            name='MeetingLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('meeting_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('meeting_type', models.JSONField(blank=True, default=list)),
                ('participants', models.TextField(blank=True, null=True)),
                ('summary_notes', models.TextField(blank=True, null=True)),
                ('skaters', models.ManyToManyField(related_name='meetings', to='api.skater')),
            ],
            options={
                'ordering': ['-meeting_date'],
            },
        ),
        migrations.CreateModel(
            name='SessionLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('object_id', models.PositiveIntegerField()),
                ('energy_stamina', models.CharField(blank=True, max_length=50, null=True)),
                ('wellbeing_focus_check_in', models.JSONField(blank=True, default=list)),
                ('wellbeing_mental_focus_notes', models.TextField(blank=True, null=True)),
                ('coach_notes', models.TextField(blank=True, null=True)),
                ('skater_notes', models.TextField(blank=True, null=True)),
                ('jump_focus', models.JSONField(blank=True, default=dict)),
                ('spin_focus', models.JSONField(blank=True, default=dict)),
                ('synchro_element_focus', models.JSONField(blank=True, default=dict)),
                ('athlete_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_logs', to='api.athleteseason')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_session_logs', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-session_date'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyPlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('week_start', models.DateField(unique=True)),
                ('theme', models.CharField(blank=True, max_length=255, null=True)),
                ('planned_off_ice_activities', models.JSONField(blank=True, default=list)),
                ('session_breakdown', models.JSONField(blank=True, default=dict)),
                ('athlete_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_plans', to='api.athleteseason')),
            ],
            options={
                'ordering': ['-week_start'],
            },
        ),
        migrations.CreateModel(
            name='YearlyPlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField()),
                ('peak_type', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_season_goal', models.TextField(blank=True, null=True)),
                ('athlete_seasons', models.ManyToManyField(related_name='yearly_plans', to='api.athleteseason')),
                ('coach_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yearly_plans', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Macrocycle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phase_title', models.CharField(max_length=100)),
                ('phase_start', models.DateField()),
                ('phase_end', models.DateField()),
                ('phase_focus', models.TextField(blank=True, null=True)),
                ('yearly_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macrocycles', to='api.yearlyplan')),
            ],
            options={
                'ordering': ['phase_start'],
            },
        ),
    ]
