# Generated by Django 5.2.8 on 2025-11-30 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_sessionlog_options_sessionlog_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='synchroteam',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='team',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
