# Generated by Django 5.2.8 on 2025-11-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_goal_created_by_goal_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingassignment',
            name='guest_occupants',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='teamtrip',
            name='guests',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='housingassignment',
            name='occupants',
            field=models.ManyToManyField(blank=True, related_name='trip_rooms', to='api.skater'),
        ),
    ]
