# Generated by Django 5.2.8 on 2025-11-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_skatingelement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skater',
            name='is_active',
            field=models.BooleanField(default=True, help_text='If false, skater is archived.'),
        ),
    ]
