# Generated by Django 5.2.8 on 2025-12-01 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_synchroteam_is_active_team_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skatingelement',
            options={'ordering': ['discipline_type', 'abbreviation']},
        ),
        migrations.AlterUniqueTogether(
            name='skatingelement',
            unique_together={('abbreviation', 'discipline_type')},
        ),
        migrations.AddField(
            model_name='skatingelement',
            name='base_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='skatingelement',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='skatingelement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='planningentityaccess',
            name='access_level',
            field=models.CharField(choices=[('COACH', 'Coach'), ('GUARDIAN', 'Guardian'), ('OBSERVER', 'Observer'), ('COLLABORATOR', 'Collaborator'), ('MANAGER', 'Manager'), ('VIEWER', 'Viewer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='skatingelement',
            name='abbreviation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='skatingelement',
            name='discipline_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='skatingelement',
            name='element_name',
            field=models.CharField(max_length=255),
        ),
        migrations.RemoveField(
            model_name='skatingelement',
            name='element_category',
        ),
    ]
