# Generated by Django 5.2.8 on 2025-11-28 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_housingassignment_guest_occupants_teamtrip_guests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamtrip',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
