# Generated by Django 5.2.8 on 2025-11-29 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_teamtrip_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('COACH', 'Coach'), ('SKATER', 'Skater'), ('GUARDIAN', 'Guardian'), ('OBSERVER', 'Observer'), ('COLLABORATOR', 'Collaborator'), ('MANAGER', 'Team Manager'), ('ATHLETE', 'Athlete'), ('PARENT', 'Parent')], max_length=20),
        ),
    ]
