# Generated by Django 5.2.8 on 2025-12-04 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_skatingelement_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='skatingelement',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='skatingelement',
            name='goe_scale',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='skatingelement',
            name='is_standard',
            field=models.BooleanField(default=True),
        ),
    ]
