# Generated by Django 5.2.8 on 2025-11-19 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_skater_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='skater',
            name='federation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.federation'),
        ),
    ]
