# Generated by Django 5.2.8 on 2025-11-19 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_skater_federation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skater_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('guardian_name', models.CharField(blank=True, max_length=255, null=True)),
                ('guardian_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('relevant_medical_notes', models.TextField(blank=True, help_text='Allergies, conditions, etc.', null=True)),
                ('skater', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='api.skater')),
            ],
        ),
    ]
