# Generated by Django 5.2.8 on 2025-12-04 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_skatingelement_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionlog',
            name='element_attempts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sessionlog',
            name='program_runs',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
