# Generated by Django 5.2.8 on 2025-11-29 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_invitation_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planningentityaccess',
            name='access_level',
            field=models.CharField(choices=[('COACH', 'Coach'), ('GUARDIAN', 'Guardian'), ('OBSERVER', 'Observer')], max_length=20),
        ),
    ]
