# Generated by Django 5.2.8 on 2025-11-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_athleteprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='athleteseason',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athleteseason',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='athleteseason',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
