# Generated by Django 4.2.27 on 2025-12-16 02:52

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_sessionlog_element_attempts_sessionlog_program_runs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteprofile',
            name='emergency_contact_name',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True)),
        ),
        migrations.AlterField(
            model_name='athleteprofile',
            name='emergency_contact_phone',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=50, null=True)),
        ),
        migrations.AlterField(
            model_name='athleteprofile',
            name='guardian_email',
            field=django_cryptography.fields.encrypt(models.EmailField(blank=True, max_length=254, null=True)),
        ),
        migrations.AlterField(
            model_name='athleteprofile',
            name='guardian_name',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True)),
        ),
        migrations.AlterField(
            model_name='athleteprofile',
            name='relevant_medical_notes',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, help_text='Allergies, conditions, etc.', null=True)),
        ),
        migrations.AlterField(
            model_name='athleteprofile',
            name='skater_email',
            field=django_cryptography.fields.encrypt(models.EmailField(blank=True, max_length=254, null=True)),
        ),
        migrations.AlterField(
            model_name='sessionlog',
            name='coach_notes',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, null=True)),
        ),
        migrations.AlterField(
            model_name='sessionlog',
            name='skater_notes',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, null=True)),
        ),
    ]
