# Generated by Django 5.2.8 on 2025-11-29 18:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_planningentityaccess_access_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='athleteseason',
            options={},
        ),
        migrations.AlterModelOptions(
            name='weeklyplan',
            options={'ordering': ['week_start']},
        ),
        migrations.RemoveField(
            model_name='gapanalysis',
            name='elements',
        ),
        migrations.RemoveField(
            model_name='gapanalysis',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='weeklyplan',
            name='planned_off_ice_activities',
        ),
        migrations.AddField(
            model_name='gapanalysis',
            name='elements_status',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='yearlyplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yearlyplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='athleteseason',
            name='primary_coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coached_seasons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='macrocycle',
            name='component_focus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='macrocycle',
            name='mental_focus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='macrocycle',
            name='physical_focus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='macrocycle',
            name='technical_focus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yearlyplan',
            name='coach_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='yearly_plans', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='yearlyplan',
            name='peak_type',
            field=models.CharField(choices=[('Single Peak', 'Single Peak'), ('Double Peak', 'Double Peak'), ('Triple Peak', 'Triple Peak'), ('Development', 'Development')], default='Single Peak', max_length=50),
        ),
    ]
