# Generated by Django 4.2.27 on 2025-12-16 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_athleteprofile_emergency_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='federation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='federation',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='federation_logos/'),
        ),
        migrations.AddField(
            model_name='federation',
            name='support_tier',
            field=models.CharField(choices=[('BASIC', 'Basic - Name only'), ('ENHANCED', 'Enhanced - Full level data'), ('PARTNER', 'Partner - Custom integration')], default='BASIC', max_length=20),
        ),
        migrations.AddField(
            model_name='federation',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FederationLevelContribution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('level_code', models.CharField(max_length=50)),
                ('capabilities', models.JSONField(default=dict)),
                ('data_source', models.URLField(help_text='Required link to rulebook')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('federation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='api.federation')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='federation_contributions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FederationLevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('level_code', models.CharField(help_text='Internal code (e.g. STAR_5)', max_length=50)),
                ('display_name', models.CharField(help_text='Human readable name', max_length=100)),
                ('sort_order', models.IntegerField(default=0, help_text='For progression ordering')),
                ('capabilities', models.JSONField(blank=True, default=dict)),
                ('data_source', models.URLField(blank=True, help_text='Link to rulebook/source', null=True)),
                ('verified', models.BooleanField(default=False)),
                ('federation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='api.federation')),
            ],
            options={
                'ordering': ['sort_order'],
                'unique_together': {('federation', 'level_code')},
            },
        ),
        migrations.AddField(
            model_name='singlesentity',
            name='current_level_structured',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skaters_at_level', to='api.federationlevel'),
        ),
    ]
