# Generated by Django 5.2.8 on 2025-11-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_athleteseason_end_date_athleteseason_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='target_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
