# Generated by Django 5.2.8 on 2025-11-19 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_goal_start_date_goal_target_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionlog',
            name='session_rating',
            field=models.IntegerField(default=3, help_text='1-5 Star Rating'),
        ),
    ]
