# Generated by Django 4.2.27 on 2025-12-16 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_organization_organizationinvite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyplan',
            name='max_session_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='max_session_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PlannedSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=10)),
                ('planned_time', models.TimeField(blank=True, null=True)),
                ('planned_duration', models.IntegerField(help_text='Duration in minutes')),
                ('session_type', models.CharField(choices=[('ON_ICE', 'On Ice'), ('OFF_ICE', 'Off Ice'), ('CLASS', 'Class / Dance'), ('CONDITIONING', 'Conditioning'), ('PROGRAM_DEVELOPMENT', 'Program Development'), ('CHOREOGRAPHY', 'Choreography'), ('MUSIC_EDIT', 'Music Edit'), ('CLINIC', 'Clinic / Seminar'), ('SHOW', 'Ice Show'), ('EXHIBITION', 'Exhibition'), ('TEST_SESSION', 'Test Session'), ('COMPETITION', 'Competition'), ('TRAVEL', 'Travel'), ('REST', 'Rest Day'), ('RECOVERY', 'Active Recovery'), ('OTHER', 'Other')], default='ON_ICE', max_length=20)),
                ('event_name', models.CharField(blank=True, max_length=255, null=True)),
                ('event_location', models.CharField(blank=True, max_length=255, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('focus', models.TextField(blank=True, null=True)),
                ('planned_elements', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('COMPLETED', 'Completed'), ('MISSED', 'Missed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sessions', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_sessions', to='api.program')),
                ('weekly_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_sessions', to='api.weeklyplan')),
                ('yearly_plan', models.ForeignKey(blank=True, help_text='Link to specific discipline plan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='api.yearlyplan')),
            ],
            options={
                'ordering': ['day_of_week', 'planned_time'],
            },
        ),
    ]
