# Generated by Django 5.2.8 on 2025-11-19 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_sessionlog_session_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionlog',
            name='sentiment_emoji',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sessionlog',
            name='energy_stamina',
            field=models.IntegerField(default=3, help_text='1-5 Rating'),
        ),
    ]
