# Generated by Django 5.2.8 on 2025-11-20 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_sessionlog_sentiment_emoji_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('location_name', models.CharField(blank=True, help_text='Arena or Venue Name', max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('province_state', models.CharField(max_length=100)),
                ('country', models.CharField(default='Canada', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_competitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField()),
                ('level', models.CharField(max_length=100)),
                ('placement', models.IntegerField(blank=True, null=True)),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('segment_scores', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.competition')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='SkaterTest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField()),
                ('test_name', models.CharField(max_length=255)),
                ('test_date', models.DateField(blank=True, null=True)),
                ('result', models.CharField(choices=[('Pass', 'Pass'), ('Retry', 'Retry'), ('Honors', 'Pass with Honors')], max_length=50)),
                ('evaluator_notes', models.TextField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
