# Generated by Django 5.2.8 on 2025-11-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_competition_competitionresult_skatertest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='country',
            field=models.CharField(default='CA', max_length=100),
        ),
        migrations.AlterField(
            model_name='competition',
            name='province_state',
            field=models.CharField(help_text='Province or State Code (e.g. AB, CA)', max_length=100),
        ),
    ]
