# Generated by Django 5.2.8 on 2025-11-20 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_competition_country_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competitionresult',
            options={'ordering': ['-competition__start_date']},
        ),
        migrations.AddField(
            model_name='competitionresult',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planned'), ('REGISTERED', 'Registered'), ('COMPLETED', 'Completed')], default='COMPLETED', max_length=20),
        ),
    ]
