# Generated by Django 5.2.8 on 2025-11-21 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_competitionresult_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skatertest',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='skatertest',
            name='object_id',
        ),
        migrations.AddField(
            model_name='skatertest',
            name='skater',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='api.skater'),
        ),
        migrations.AddField(
            model_name='skatertest',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planned'), ('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('WITHDRAWN', 'Withdrawn')], default='PLANNED', max_length=20),
        ),
        migrations.AlterField(
            model_name='skatertest',
            name='result',
            field=models.CharField(blank=True, choices=[('Pass', 'Pass'), ('Retry', 'Retry'), ('Honors', 'Pass with Honors')], max_length=50, null=True),
        ),
    ]
