# Generated by Django 5.2.8 on 2025-11-21 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_skatertest_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skatertest',
            name='test_type',
            field=models.CharField(default='Skills', max_length=100),
        ),
    ]
