# Generated by Django 5.2.8 on 2025-11-21 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_skatertest_test_type'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('season', models.CharField(max_length=50)),
                ('program_category', models.CharField(choices=[('Short Program', 'Short Program'), ('Free Skate', 'Free Skate'), ('Rhythm Dance', 'Rhythm Dance'), ('Free Dance', 'Free Dance'), ('Artistic', 'Artistic'), ('Other', 'Other')], default='Free Skate', max_length=50)),
                ('music_title', models.CharField(blank=True, max_length=255, null=True)),
                ('choreographer', models.CharField(blank=True, max_length=255, null=True)),
                ('planned_elements', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
