# Generated by Django 5.2.8 on 2025-11-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Set to false if program is dropped/retired.'),
        ),
    ]
