# Generated by Django 5.2.8 on 2025-11-21 03:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_program_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionlog',
            name='session_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
