# Generated by Django 5.2.8 on 2025-11-21 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_sessionlog_session_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionresult',
            name='planned_base_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='province_state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='program',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='skatertest',
            name='skater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='api.skater'),
        ),
        migrations.AlterField(
            model_name='skatingelement',
            name='discipline_type',
            field=models.CharField(choices=[('JUMP', 'Jump'), ('SPIN', 'Spin'), ('SPIN COMBINATION', 'Spin Combination'), ('STEP SEQUENCE', 'Step Sequence'), ('CHOREOGRAPHIC ELEMENT', 'Choreographic Element'), ('THROW JUMP', 'Throw Jump'), ('TWIST LIFT', 'Twist Lift'), ('PAIR SPIN', 'Pair Spin'), ('PAIR SPIN COMBINATION', 'Pair Spin Combination'), ('PAIR LIFT', 'Pair Lift'), ('DEATH SPIRAL', 'Death Spiral'), ('PAIR ELEMENT', 'Pair Element'), ('PATTERN DANCE', 'Pattern Dance'), ('PATTERN DANCE ELEMENT', 'Pattern Dance Element'), ('DANCE STEP', 'Dance Step'), ('DANCE SPIN', 'Dance Spin'), ('DANCE LIFT', 'Dance Lift'), ('DANCE TWIZZLE', 'Dance Twizzle'), ('DANCE STEP/TURN', 'Dance Step/Turn'), ('DANCE EDGE ELEMENT', 'Dance Edge Element'), ('CHOREOGRAPHIC', 'Choreographic'), ('SYNCHRO ARTISTIC', 'Synchro Artistic'), ('SYNCHRO CREATIVE', 'Synchro Creative'), ('SYNCHRO LIFT', 'Synchro Lift'), ('SYNCHRO INTERSECTION', 'Synchro Intersection'), ('SYNCHRO FORMATION', 'Synchro Formation'), ('SYNCHRO PIVOTING', 'Synchro Pivoting'), ('SYNCHRO SPIN', 'Synchro Spin'), ('SYNCHRO TWIZZLE', 'Synchro Twizzle'), ('SYNCHRO', 'Synchro Mixed'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
    ]
