# Generated by Django 5.2.8 on 2025-11-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_competitionresult_planned_base_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='est_base_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
