# Generated by Django 5.2.8 on 2025-11-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_program_est_base_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionresult',
            name='detailed_protocol',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
