# Generated by Django 5.2.8 on 2025-11-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_competitionresult_detailed_protocol'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionresult',
            name='detail_sheet',
            field=models.FileField(blank=True, null=True, upload_to='competitions/protocols/'),
        ),
        migrations.AddField(
            model_name='competitionresult',
            name='video_url',
            field=models.URLField(blank=True, help_text='Link to full event video', null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='costume_design',
            field=models.FileField(blank=True, help_text='Sketch or PDF', null=True, upload_to='programs/design/'),
        ),
        migrations.AddField(
            model_name='program',
            name='costume_photo',
            field=models.ImageField(blank=True, help_text='Final look', null=True, upload_to='programs/photos/'),
        ),
        migrations.AddField(
            model_name='program',
            name='hair_photo',
            field=models.ImageField(blank=True, null=True, upload_to='programs/photos/'),
        ),
        migrations.AddField(
            model_name='program',
            name='music_file',
            field=models.FileField(blank=True, null=True, upload_to='programs/music/'),
        ),
        migrations.AddField(
            model_name='skatertest',
            name='test_sheet',
            field=models.FileField(blank=True, null=True, upload_to='tests/sheets/'),
        ),
        migrations.AddField(
            model_name='skatertest',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
