# Generated by Django 5.2.8 on 2025-11-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_competitionresult_detail_sheet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteseason',
            name='season',
            field=models.CharField(max_length=50),
        ),
    ]
