# Generated by Django 5.2.8 on 2025-11-22 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_athleteseason_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyplan',
            name='week_start',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='weeklyplan',
            unique_together={('athlete_season', 'week_start')},
        ),
    ]
