# Generated by Django 5.2.8 on 2025-11-22 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_weeklyplan_week_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='synchroteam',
            name='roster',
            field=models.ManyToManyField(blank=True, related_name='synchro_teams', to='api.skater'),
        ),
    ]
