# Generated by Django 5.2.8 on 2025-11-22 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_synchroteam_roster'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='athleteseason',
            options={'ordering': ['-season']},
        ),
        migrations.AlterUniqueTogether(
            name='athleteseason',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='athleteseason',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='athleteseason',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='athleteseason',
            name='skater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='athlete_seasons', to='api.skater'),
        ),
    ]
