# Generated by Django 5.2.8 on 2025-11-22 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_athleteseason_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='costume_design',
        ),
        migrations.RemoveField(
            model_name='program',
            name='costume_photo',
        ),
        migrations.RemoveField(
            model_name='program',
            name='hair_photo',
        ),
        migrations.CreateModel(
            name='ProgramAsset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='programs/assets/')),
                ('asset_type', models.CharField(choices=[('COSTUME', 'Costume'), ('HAIR', 'Hair & Makeup'), ('DESIGN', 'Design/Sketch'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='api.program')),
            ],
        ),
    ]
