# Generated by Django 5.2.8 on 2025-11-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_program_costume_design_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionlog',
            name='attendance',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
