# Generated by Django 5.2.8 on 2025-11-22 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_sessionlog_attendance'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamTrip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('flight_info', models.TextField(blank=True, help_text='Group flight details', null=True)),
                ('hotel_info', models.TextField(blank=True, help_text='Hotel block info', null=True)),
                ('transport_notes', models.TextField(blank=True, help_text='Bus schedule notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='api.competition')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('activity', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('TRAVEL', 'Travel'), ('ICE', 'On Ice'), ('OFF_ICE', 'Off Ice / Warmup'), ('MEAL', 'Meal'), ('MEETING', 'Meeting'), ('COMPETITION', 'Competition'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='api.teamtrip')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='HousingAssignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room_number', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('occupants', models.ManyToManyField(related_name='trip_rooms', to='api.skater')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooming_list', to='api.teamtrip')),
            ],
        ),
    ]
