# Generated by Django 5.2.8 on 2025-11-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_teamtrip_itineraryitem_housingassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamtrip',
            name='flight_info',
        ),
        migrations.RemoveField(
            model_name='teamtrip',
            name='transport_notes',
        ),
        migrations.AddField(
            model_name='teamtrip',
            name='ground_transport_notes',
            field=models.TextField(blank=True, help_text='Transport at destination (e.g. Shuttle bus to rink)', null=True),
        ),
        migrations.AddField(
            model_name='teamtrip',
            name='travel_segments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='teamtrip',
            name='hotel_info',
            field=models.TextField(blank=True, help_text='Hotel name, address, booking block', null=True),
        ),
    ]
