# Generated by Django 5.2.8 on 2025-11-23 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_remove_teamtrip_flight_info_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='macrocycle',
            name='component_focus',
            field=models.TextField(blank=True, help_text='Artistic, Performance', null=True),
        ),
        migrations.AddField(
            model_name='macrocycle',
            name='mental_focus',
            field=models.TextField(blank=True, help_text='Psychology, Lifestyle', null=True),
        ),
        migrations.AddField(
            model_name='macrocycle',
            name='physical_focus',
            field=models.TextField(blank=True, help_text='Strength, Conditioning', null=True),
        ),
        migrations.AddField(
            model_name='macrocycle',
            name='technical_focus',
            field=models.TextField(blank=True, help_text='Elements, Strategy', null=True),
        ),
        migrations.CreateModel(
            name='GapAnalysis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('elements', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
