# ~/development/skateplan/docker-compose.yml
include:
  - path: infra/docker-compose.yml
    env_file: infra/.env

services:
  backend:
    build: ./backend
    container_name: skateplan-backend
    restart: always
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - infra/.env
    environment:
      # Connection to the DB in the 'infra' stack
      # Public URL for CORS (Browser access)
      - POSTGRES_SERVER=db
      - API_EXTERNAL_URL=https://api.skateplan.bradnet.net
    depends_on:
      db:
        condition: service_healthy
    networks:
      - default
    user: "${DOCKER_UID}:${DOCKER_GID}"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: skateplan-frontend
    restart: always
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm next dev --webpack"
    environment:
      - NEXT_PUBLIC_API_URL=https://api.skateplan.bradnet.net/api/v1
      - API_INTERNAL_URL=http://backend:8000
      - NEXT_TURBOPACK=0
    depends_on:
      - backend
    networks:
      - default
    user: "${DOCKER_UID}:${DOCKER_GID}"
    volumes:
      - ./frontend:/app

# This ensures all services share the network created by the 'include'
networks:
  default:
