"""add_events_and_competitions

Revision ID: 3cced125cf5f
Revises: a61ae602f8df
Create Date: 2026-03-05 17:36:14.044046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = '3cced125cf5f'
down_revision: Union[str, Sequence[str], None] = 'a61ae602f8df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # (KEEP ALL YOUR ACTUAL COLUMNS INSIDE THESE TWO BLOCKS)
    op.create_table('competitions',
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('start_date', sa.Date(), nullable=False),
        # ... etc ...
    )
    op.create_table('skater_events',
        sa.Column('skater_id', sa.Uuid(), nullable=False),
        sa.Column('event_type', sa.Enum('COMPETITION', 'TEST_DAY', 'SIMULATION', 'CAMP', name='eventtype'), nullable=False),
        # ... etc ...
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skater_events')
    op.drop_table('competitions')
    # ### end Alembic commands ###
