"""unified profiles schema with partnerships and coach links

Revision ID: 3d1b22a46704
Revises:
Create Date: 2026-01-13 23:44:59.801135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d1b22a46704'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partnerships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('skater_a_id', sa.Uuid(), nullable=False),
    sa.Column('skater_b_id', sa.Uuid(), nullable=False),
    sa.Column('discipline', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('team_level', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['skater_a_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['skater_b_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('programs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('skater_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('discipline', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('season', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('music_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['skater_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programs_skater_id'), 'programs', ['skater_id'], unique=False)
    op.create_table('skater_coach_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('skater_id', sa.Uuid(), nullable=False),
    sa.Column('coach_id', sa.Uuid(), nullable=False),
    sa.Column('permission_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['skater_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skater_coach_links_coach_id'), 'skater_coach_links', ['coach_id'], unique=False)
    op.create_index(op.f('ix_skater_coach_links_skater_id'), 'skater_coach_links', ['skater_id'], unique=False)
    op.create_table('program_elements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('program_id', sa.Uuid(), nullable=False),
    sa.Column('element_id', sa.Uuid(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['element_id'], ['elements.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_elements_program_id'), 'program_elements', ['program_id'], unique=False)
    op.create_table('program_asset_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('program_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('asset_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['program_assets.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_asset_links_asset_id'), 'program_asset_links', ['asset_id'], unique=False)
    op.create_index(op.f('ix_program_asset_links_program_id'), 'program_asset_links', ['program_id'], unique=False)
    op.drop_table('benchmark_metrics')
    op.drop_index(op.f('ix_benchmark_profiles_skater_id'), table_name='benchmark_profiles')
    op.drop_table('benchmark_profiles')
    op.add_column('benchmark_sessions', sa.Column('partnership_id', sa.Uuid(), nullable=True))
    op.alter_column('benchmark_sessions', 'skater_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('benchmark_sessions_skater_id_fkey'), 'benchmark_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'benchmark_sessions', 'partnerships', ['partnership_id'], ['id'])
    op.create_foreign_key(None, 'benchmark_sessions', 'profiles', ['skater_id'], ['id'])
    op.add_column('profiles', sa.Column('level', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('profiles', sa.Column('is_active', sa.Boolean(), nullable=True, server_default=sa.text('true')))
    op.add_column('profiles', sa.Column('federation', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('profiles', sa.Column('isu_level_anchor', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # Update existing rows to have is_active=True
    op.execute('UPDATE profiles SET is_active = true WHERE is_active IS NULL')
    # Now make is_active NOT NULL
    op.alter_column('profiles', 'is_active', nullable=False)
    op.alter_column('profiles', 'is_adaptive',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('profiles', 'active_disciplines',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('program_assets', 'meta_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('program_assets', 'meta_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('profiles', 'active_disciplines',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('profiles', 'is_adaptive',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('profiles', 'isu_level_anchor')
    op.drop_column('profiles', 'federation')
    op.drop_column('profiles', 'is_active')
    op.drop_column('profiles', 'level')
    op.drop_constraint(None, 'benchmark_sessions', type_='foreignkey')
    op.drop_constraint(None, 'benchmark_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('benchmark_sessions_skater_id_fkey'), 'benchmark_sessions', 'skaters', ['skater_id'], ['id'])
    op.alter_column('benchmark_sessions', 'skater_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('benchmark_sessions', 'partnership_id')
    op.create_table('benchmark_profiles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('skater_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('valid_from', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('valid_to', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('benchmark_profiles_pkey'))
    )
    op.create_index(op.f('ix_benchmark_profiles_skater_id'), 'benchmark_profiles', ['skater_id'], unique=False)
    op.create_table('benchmark_metrics',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('profile_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('target_value', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['benchmark_profiles.id'], name=op.f('benchmark_metrics_profile_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('benchmark_metrics_pkey'))
    )
    op.drop_index(op.f('ix_program_asset_links_program_id'), table_name='program_asset_links')
    op.drop_index(op.f('ix_program_asset_links_asset_id'), table_name='program_asset_links')
    op.drop_table('program_asset_links')
    op.drop_index(op.f('ix_program_elements_program_id'), table_name='program_elements')
    op.drop_table('program_elements')
    op.drop_index(op.f('ix_skater_coach_links_skater_id'), table_name='skater_coach_links')
    op.drop_index(op.f('ix_skater_coach_links_coach_id'), table_name='skater_coach_links')
    op.drop_table('skater_coach_links')
    op.drop_index(op.f('ix_programs_skater_id'), table_name='programs')
    op.drop_table('programs')
    op.drop_table('partnerships')
    # ### end Alembic commands ###
