"""sprint1 federations levels grants sessions skater_profile fks

Revision ID: 636748e0b2b6
Revises: 6591432e23eb
Create Date: 2026-09-03 17:43:38.464867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '636748e0b2b6'
down_revision: Union[str, Sequence[str], None] = '6591432e23eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('federations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('iso_code', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_federations_code'), 'federations', ['code'], unique=True)
    op.create_table('external_access_grants',
    sa.Column('grant_id', sa.Uuid(), nullable=False),
    sa.Column('training_unit_id', sa.Integer(), nullable=False),
    sa.Column('grantee_email', sa.String(length=255), nullable=False),
    sa.Column('access_tier', sa.Enum('assessor_masked', 'hpd_full', name='access_tier_enum'), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('granted_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['granted_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['training_unit_id'], ['training_units.training_unit_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('grant_id')
    )
    op.create_index(op.f('ix_external_access_grants_token'), 'external_access_grants', ['token'], unique=True)
    op.create_table('federation_streams',
    sa.Column('stream_id', sa.Integer(), nullable=False),
    sa.Column('federation_code', sa.String(length=10), nullable=False),
    sa.Column('stream_name', sa.String(length=120), nullable=False),
    sa.Column('stream_display', sa.String(length=160), nullable=True),
    sa.Column('discipline', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['federation_code'], ['federations.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('stream_id')
    )
    op.create_index(op.f('ix_federation_streams_federation_code'), 'federation_streams', ['federation_code'], unique=False)
    op.create_table('competition_levels',
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=False),
    sa.Column('level_name', sa.String(length=160), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_adult', sa.Boolean(), nullable=False),
    sa.Column('isu_anchor', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['stream_id'], ['federation_streams.stream_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('level_id')
    )
    op.create_index(op.f('ix_competition_levels_stream_id'), 'competition_levels', ['stream_id'], unique=False)
    op.create_table('training_sessions',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('training_unit_id', sa.Integer(), nullable=False),
    sa.Column('skater_id', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['skater_id'], ['skater_profiles.skater_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['training_unit_id'], ['training_units.training_unit_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_training_sessions_skater_id'), 'training_sessions', ['skater_id'], unique=False)
    op.create_index(op.f('ix_training_sessions_training_unit_id'), 'training_sessions', ['training_unit_id'], unique=False)
    op.add_column('skater_profiles', sa.Column('federation_registration_id', sa.String(length=120), nullable=True))
    op.add_column('skater_profiles', sa.Column('current_level_id', sa.Integer(), nullable=True))
    op.add_column('skater_profiles', sa.Column('medical_notes', sa.Text(), nullable=True))
    # Sprint 0 federation_id was a free-text VARCHAR placeholder; replace it with
    # a normalized integer FK. The column held no meaningful data yet, so a
    # drop + add is safe (avoids an implicit VARCHAR->Integer cast error).
    op.drop_column('skater_profiles', 'federation_id')
    op.add_column('skater_profiles', sa.Column('federation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'skater_profiles', 'federations', ['federation_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'skater_profiles', 'competition_levels', ['current_level_id'], ['level_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'skater_profiles', type_='foreignkey')
    op.drop_constraint(None, 'skater_profiles', type_='foreignkey')
    op.drop_column('skater_profiles', 'federation_id')
    op.add_column('skater_profiles', sa.Column('federation_id', sa.VARCHAR(length=120), nullable=True))
    op.drop_column('skater_profiles', 'medical_notes')
    op.drop_column('skater_profiles', 'current_level_id')
    op.drop_column('skater_profiles', 'federation_registration_id')
    op.drop_index(op.f('ix_training_sessions_training_unit_id'), table_name='training_sessions')
    op.drop_index(op.f('ix_training_sessions_skater_id'), table_name='training_sessions')
    op.drop_table('training_sessions')
    op.drop_index(op.f('ix_competition_levels_stream_id'), table_name='competition_levels')
    op.drop_table('competition_levels')
    op.drop_index(op.f('ix_federation_streams_federation_code'), table_name='federation_streams')
    op.drop_table('federation_streams')
    op.drop_index(op.f('ix_external_access_grants_token'), table_name='external_access_grants')
    op.drop_table('external_access_grants')
    op.drop_index(op.f('ix_federations_code'), table_name='federations')
    op.drop_table('federations')
    # ### end Alembic commands ###
