"""initial schema

Revision ID: 6591432e23eb
Revises: 
Create Date: 2026-09-03 17:25:55.458234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6591432e23eb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('safesport_text_history_ledgers',
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('target_table_name', sa.String(length=255), nullable=False),
    sa.Column('target_record_id', sa.String(length=255), nullable=False),
    sa.Column('target_column_name', sa.String(length=255), nullable=False),
    sa.Column('historical_text_value', sa.Text(), nullable=True),
    sa.Column('revised_by_actor_id', sa.Integer(), nullable=True),
    sa.Column('source_ip_address', sa.String(length=64), nullable=True),
    sa.Column('revision_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_table('scale_of_values',
    sa.Column('abbreviation', sa.String(length=50), nullable=False),
    sa.Column('element_name', sa.String(length=255), nullable=False),
    sa.Column('base_value', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('goe_minus_5', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('goe_minus_4', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('goe_minus_3', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('goe_minus_2', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('goe_minus_1', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('goe_plus_1', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('goe_plus_2', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('goe_plus_3', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('goe_plus_4', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('goe_plus_5', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('abbreviation')
    )
    op.create_table('training_units',
    sa.Column('training_unit_id', sa.Integer(), nullable=False),
    sa.Column('discipline_type', sa.Enum('singles', name='discipline_type_enum'), nullable=False),
    sa.Column('unit_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('training_unit_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('system_role', sa.Enum('coach', 'athlete', 'parent', 'admin', name='system_role_enum'), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('coach_assignments',
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('coach_user_id', sa.Integer(), nullable=False),
    sa.Column('training_unit_id', sa.Integer(), nullable=False),
    sa.Column('role_in_unit', sa.Enum('primary', 'secondary', 'choreographer', name='role_in_unit_enum'), nullable=False),
    sa.ForeignKeyConstraint(['coach_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['training_unit_id'], ['training_units.training_unit_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_table('skater_profiles',
    sa.Column('skater_id', sa.Integer(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('home_club', sa.String(length=255), nullable=True),
    sa.Column('federation_id', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['skater_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('skater_id')
    )
    op.create_table('account_proxy_links',
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('skater_id', sa.Integer(), nullable=False),
    sa.Column('parent_user_id', sa.Integer(), nullable=False),
    sa.Column('is_active_observer', sa.Boolean(), nullable=False),
    sa.Column('access_state', sa.Enum('active', 'revoked_by_adult', name='access_state_enum'), nullable=False),
    sa.ForeignKeyConstraint(['parent_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skater_id'], ['skater_profiles.skater_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('link_id')
    )
    op.create_table('training_unit_roster',
    sa.Column('roster_entry_id', sa.Integer(), nullable=False),
    sa.Column('training_unit_id', sa.Integer(), nullable=False),
    sa.Column('skater_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['skater_id'], ['skater_profiles.skater_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['training_unit_id'], ['training_units.training_unit_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('roster_entry_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_unit_roster')
    op.drop_table('account_proxy_links')
    op.drop_table('skater_profiles')
    op.drop_table('coach_assignments')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('training_units')
    op.drop_table('scale_of_values')
    op.drop_table('safesport_text_history_ledgers')
    # ### end Alembic commands ###
