"""sprint4_training_session_logs_and_attempts

Revision ID: 826799aa7ee1
Revises: 4dca604bcaba
Create Date: 2026-09-03 19:52:56.026188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '826799aa7ee1'
down_revision: Union[str, Sequence[str], None] = '4dca604bcaba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_session_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('skater_id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=True),
    sa.Column('session_type', sa.String(length=30), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('rpe', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rpe >= 1 AND rpe <= 10', name='ck_training_session_logs_rpe_range'),
    sa.ForeignKeyConstraint(['skater_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_session_logs_session_date'), 'training_session_logs', ['session_date'], unique=False)
    op.create_index(op.f('ix_training_session_logs_skater_id'), 'training_session_logs', ['skater_id'], unique=False)
    op.create_table('jump_attempt_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('element_code', sa.String(length=50), nullable=False),
    sa.Column('outcome', sa.String(length=30), nullable=False),
    sa.Column('attempts_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['training_session_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jump_attempt_logs_session_id'), 'jump_attempt_logs', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jump_attempt_logs_session_id'), table_name='jump_attempt_logs')
    op.drop_table('jump_attempt_logs')
    op.drop_index(op.f('ix_training_session_logs_skater_id'), table_name='training_session_logs')
    op.drop_index(op.f('ix_training_session_logs_session_date'), table_name='training_session_logs')
    op.drop_table('training_session_logs')
    # ### end Alembic commands ###
