"""add_equipment_tables

Revision ID: ae8d4b297495
Revises: a76241370feb
Create Date: 2026-03-03 02:23:28.646961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'ae8d4b297495'
down_revision: Union[str, Sequence[str], None] = 'a76241370feb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adult_age_classes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('min_age', sa.Integer(), nullable=False),
    sa.Column('max_age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adult_age_classes_code'), 'adult_age_classes', ['code'], unique=False)
    op.create_table('competitive_levels',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('federation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('discipline', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('isu_anchor', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_levels',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('federation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('discipline', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('level_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sub_tests', sa.JSON(), nullable=False),
    sa.Column('completion_rule', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('skater_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('type', sa.Enum('BOOT', 'BLADE', name='equipmenttype'), nullable=False),
    sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('size', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['skater_id'], ['skaters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_is_active'), 'equipment', ['is_active'], unique=False)
    op.create_index(op.f('ix_equipment_skater_id'), 'equipment', ['skater_id'], unique=False)
    op.create_index(op.f('ix_equipment_type'), 'equipment', ['type'], unique=False)
    op.create_table('maintenance_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('equipment_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('maintenance_type', sa.Enum('SHARPENING', 'MOUNTING', 'WATERPROOFING', 'REPAIR', 'REPLACEMENT', 'OTHER', name='maintenancetype'), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('technician', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('specifications', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_logs_date'), 'maintenance_logs', ['date'], unique=False)
    op.create_index(op.f('ix_maintenance_logs_equipment_id'), 'maintenance_logs', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_maintenance_logs_maintenance_type'), 'maintenance_logs', ['maintenance_type'], unique=False)
    op.drop_index(op.f('ix_levels_is_adult'), table_name='levels')
    op.drop_index(op.f('ix_levels_level_order'), table_name='levels')
    op.drop_index(op.f('ix_levels_stream_id'), table_name='levels')
    op.drop_table('levels')
    op.drop_index(op.f('ix_streams_discipline'), table_name='streams')
    op.drop_index(op.f('ix_streams_federation_code'), table_name='streams')
    op.drop_table('streams')
    op.alter_column('benchmark_profiles', 'description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_index(op.f('idx_profile_active'), table_name='benchmark_profiles')
    op.drop_index(op.f('idx_profile_coach'), table_name='benchmark_profiles')
    op.drop_constraint(op.f('uq_coach_profile_name'), 'benchmark_profiles', type_='unique')
    op.create_index(op.f('ix_benchmark_profiles_coach_id'), 'benchmark_profiles', ['coach_id'], unique=False)
    op.drop_constraint(op.f('benchmark_profiles_coach_id_fkey'), 'benchmark_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'benchmark_profiles', 'profiles', ['coach_id'], ['id'])
    op.add_column('benchmark_sessions', sa.Column('team_id', sa.Uuid(), nullable=True))
    op.alter_column('benchmark_sessions', 'skater_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('benchmark_sessions', 'notes',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_index(op.f('idx_session_date'), table_name='benchmark_sessions')
    op.drop_index(op.f('idx_session_profile'), table_name='benchmark_sessions')
    op.drop_index(op.f('idx_session_skater'), table_name='benchmark_sessions')
    op.create_index(op.f('ix_benchmark_sessions_profile_id'), 'benchmark_sessions', ['profile_id'], unique=False)
    op.create_index(op.f('ix_benchmark_sessions_skater_id'), 'benchmark_sessions', ['skater_id'], unique=False)
    op.create_index(op.f('ix_benchmark_sessions_team_id'), 'benchmark_sessions', ['team_id'], unique=False)
    op.drop_constraint(op.f('benchmark_sessions_skater_id_fkey'), 'benchmark_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'benchmark_sessions', 'profiles', ['skater_id'], ['id'])
    op.alter_column('federations', 'iso_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('federations', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_constraint(op.f('uq_federations_code'), 'federations', type_='unique')
    op.drop_index(op.f('idx_gap_skater'), table_name='gap_analyses')
    op.drop_index(op.f('idx_gap_team'), table_name='gap_analyses')
    op.drop_index(op.f('idx_gap_updated'), table_name='gap_analyses')
    op.create_index(op.f('ix_gap_analyses_last_updated'), 'gap_analyses', ['last_updated'], unique=False)
    op.create_index(op.f('ix_gap_analyses_skater_id'), 'gap_analyses', ['skater_id'], unique=False)
    op.create_index(op.f('ix_gap_analyses_team_id'), 'gap_analyses', ['team_id'], unique=False)
    op.drop_constraint(op.f('gap_analyses_team_id_fkey'), 'gap_analyses', type_='foreignkey')
    op.drop_constraint(op.f('gap_analyses_skater_id_fkey'), 'gap_analyses', type_='foreignkey')
    op.create_foreign_key(None, 'gap_analyses', 'profiles', ['skater_id'], ['id'])
    op.create_foreign_key(None, 'gap_analyses', 'teams', ['team_id'], ['id'])
    op.alter_column('gap_analysis_entries', 'notes',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('gap_analysis_entries', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_constraint(op.f('gap_analysis_entries_gap_analysis_id_metric_id_key'), 'gap_analysis_entries', type_='unique')
    op.drop_index(op.f('idx_entry_active'), table_name='gap_analysis_entries')
    op.drop_index(op.f('idx_entry_gap'), table_name='gap_analysis_entries')
    op.drop_index(op.f('idx_entry_metric'), table_name='gap_analysis_entries')
    op.create_index(op.f('ix_gap_analysis_entries_gap_analysis_id'), 'gap_analysis_entries', ['gap_analysis_id'], unique=False)
    op.create_index(op.f('ix_gap_analysis_entries_is_active'), 'gap_analysis_entries', ['is_active'], unique=False)
    op.create_index(op.f('ix_gap_analysis_entries_metric_id'), 'gap_analysis_entries', ['metric_id'], unique=False)
    op.drop_constraint(op.f('gap_analysis_entries_gap_analysis_id_fkey'), 'gap_analysis_entries', type_='foreignkey')
    op.create_foreign_key(None, 'gap_analysis_entries', 'gap_analyses', ['gap_analysis_id'], ['id'])
    op.drop_index(op.f('idx_pm_metric'), table_name='profile_metrics')
    op.drop_index(op.f('idx_pm_profile'), table_name='profile_metrics')
    op.drop_constraint(op.f('uq_profile_metric'), 'profile_metrics', type_='unique')
    op.create_index(op.f('ix_profile_metrics_metric_id'), 'profile_metrics', ['metric_id'], unique=False)
    op.create_index(op.f('ix_profile_metrics_profile_id'), 'profile_metrics', ['profile_id'], unique=False)
    op.drop_constraint(op.f('profile_metrics_profile_id_fkey'), 'profile_metrics', type_='foreignkey')
    op.drop_constraint(op.f('profile_metrics_metric_id_fkey'), 'profile_metrics', type_='foreignkey')
    op.create_foreign_key(None, 'profile_metrics', 'benchmark_profiles', ['profile_id'], ['id'])
    op.create_foreign_key(None, 'profile_metrics', 'metric_definitions', ['metric_id'], ['id'])
    op.drop_constraint(op.f('session_elements_session_id_fkey'), 'session_elements', type_='foreignkey')
    op.create_foreign_key(None, 'session_elements', 'sessions', ['session_id'], ['id'])
    op.drop_index(op.f('idx_result_metric'), table_name='session_results')
    op.drop_index(op.f('idx_result_session'), table_name='session_results')
    op.drop_constraint(op.f('uq_session_metric'), 'session_results', type_='unique')
    op.create_index(op.f('ix_session_results_metric_id'), 'session_results', ['metric_id'], unique=False)
    op.create_index(op.f('ix_session_results_session_id'), 'session_results', ['session_id'], unique=False)
    op.drop_constraint(op.f('session_results_session_id_fkey'), 'session_results', type_='foreignkey')
    op.create_foreign_key(None, 'session_results', 'benchmark_sessions', ['session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session_results', type_='foreignkey')
    op.create_foreign_key(op.f('session_results_session_id_fkey'), 'session_results', 'benchmark_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_session_results_session_id'), table_name='session_results')
    op.drop_index(op.f('ix_session_results_metric_id'), table_name='session_results')
    op.create_unique_constraint(op.f('uq_session_metric'), 'session_results', ['session_id', 'metric_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_result_session'), 'session_results', ['session_id'], unique=False)
    op.create_index(op.f('idx_result_metric'), 'session_results', ['metric_id'], unique=False)
    op.drop_constraint(None, 'session_elements', type_='foreignkey')
    op.create_foreign_key(op.f('session_elements_session_id_fkey'), 'session_elements', 'sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'profile_metrics', type_='foreignkey')
    op.drop_constraint(None, 'profile_metrics', type_='foreignkey')
    op.create_foreign_key(op.f('profile_metrics_metric_id_fkey'), 'profile_metrics', 'metric_definitions', ['metric_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('profile_metrics_profile_id_fkey'), 'profile_metrics', 'benchmark_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_profile_metrics_profile_id'), table_name='profile_metrics')
    op.drop_index(op.f('ix_profile_metrics_metric_id'), table_name='profile_metrics')
    op.create_unique_constraint(op.f('uq_profile_metric'), 'profile_metrics', ['profile_id', 'metric_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_pm_profile'), 'profile_metrics', ['profile_id'], unique=False)
    op.create_index(op.f('idx_pm_metric'), 'profile_metrics', ['metric_id'], unique=False)
    op.drop_constraint(None, 'gap_analysis_entries', type_='foreignkey')
    op.create_foreign_key(op.f('gap_analysis_entries_gap_analysis_id_fkey'), 'gap_analysis_entries', 'gap_analyses', ['gap_analysis_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_gap_analysis_entries_metric_id'), table_name='gap_analysis_entries')
    op.drop_index(op.f('ix_gap_analysis_entries_is_active'), table_name='gap_analysis_entries')
    op.drop_index(op.f('ix_gap_analysis_entries_gap_analysis_id'), table_name='gap_analysis_entries')
    op.create_index(op.f('idx_entry_metric'), 'gap_analysis_entries', ['metric_id'], unique=False)
    op.create_index(op.f('idx_entry_gap'), 'gap_analysis_entries', ['gap_analysis_id'], unique=False)
    op.create_index(op.f('idx_entry_active'), 'gap_analysis_entries', ['is_active'], unique=False)
    op.create_unique_constraint(op.f('gap_analysis_entries_gap_analysis_id_metric_id_key'), 'gap_analysis_entries', ['gap_analysis_id', 'metric_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('gap_analysis_entries', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('gap_analysis_entries', 'notes',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'gap_analyses', type_='foreignkey')
    op.drop_constraint(None, 'gap_analyses', type_='foreignkey')
    op.create_foreign_key(op.f('gap_analyses_skater_id_fkey'), 'gap_analyses', 'profiles', ['skater_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('gap_analyses_team_id_fkey'), 'gap_analyses', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_gap_analyses_team_id'), table_name='gap_analyses')
    op.drop_index(op.f('ix_gap_analyses_skater_id'), table_name='gap_analyses')
    op.drop_index(op.f('ix_gap_analyses_last_updated'), table_name='gap_analyses')
    op.create_index(op.f('idx_gap_updated'), 'gap_analyses', ['last_updated'], unique=False)
    op.create_index(op.f('idx_gap_team'), 'gap_analyses', ['team_id'], unique=False)
    op.create_index(op.f('idx_gap_skater'), 'gap_analyses', ['skater_id'], unique=False)
    op.create_unique_constraint(op.f('uq_federations_code'), 'federations', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('federations', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('federations', 'iso_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'benchmark_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('benchmark_sessions_skater_id_fkey'), 'benchmark_sessions', 'profiles', ['skater_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_benchmark_sessions_team_id'), table_name='benchmark_sessions')
    op.drop_index(op.f('ix_benchmark_sessions_skater_id'), table_name='benchmark_sessions')
    op.drop_index(op.f('ix_benchmark_sessions_profile_id'), table_name='benchmark_sessions')
    op.create_index(op.f('idx_session_skater'), 'benchmark_sessions', ['skater_id'], unique=False)
    op.create_index(op.f('idx_session_profile'), 'benchmark_sessions', ['profile_id'], unique=False)
    op.create_index(op.f('idx_session_date'), 'benchmark_sessions', ['recorded_at'], unique=False)
    op.alter_column('benchmark_sessions', 'notes',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('benchmark_sessions', 'skater_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('benchmark_sessions', 'team_id')
    op.drop_constraint(None, 'benchmark_profiles', type_='foreignkey')
    op.create_foreign_key(op.f('benchmark_profiles_coach_id_fkey'), 'benchmark_profiles', 'profiles', ['coach_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_benchmark_profiles_coach_id'), table_name='benchmark_profiles')
    op.create_unique_constraint(op.f('uq_coach_profile_name'), 'benchmark_profiles', ['coach_id', 'name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_profile_coach'), 'benchmark_profiles', ['coach_id'], unique=False)
    op.create_index(op.f('idx_profile_active'), 'benchmark_profiles', ['is_active'], unique=False)
    op.alter_column('benchmark_profiles', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_table('streams',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('federation_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('stream_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('stream_display', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('discipline', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['federation_code'], ['federations.code'], name=op.f('streams_federation_code_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('streams_pkey')),
    sa.UniqueConstraint('federation_code', 'stream_code', name=op.f('uq_federation_stream'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_streams_federation_code'), 'streams', ['federation_code'], unique=False)
    op.create_index(op.f('ix_streams_discipline'), 'streams', ['discipline'], unique=False)
    op.create_table('levels',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('stream_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('level_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('level_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_adult', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('is_system', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('isu_anchor', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_by_coach_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by_coach_id'], ['profiles.id'], name=op.f('levels_created_by_coach_id_fkey')),
    sa.ForeignKeyConstraint(['stream_id'], ['streams.id'], name=op.f('levels_stream_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('levels_pkey')),
    sa.UniqueConstraint('stream_id', 'level_name', name=op.f('uq_stream_level'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_levels_stream_id'), 'levels', ['stream_id'], unique=False)
    op.create_index(op.f('ix_levels_level_order'), 'levels', ['level_order'], unique=False)
    op.create_index(op.f('ix_levels_is_adult'), 'levels', ['is_adult'], unique=False)
    op.drop_index(op.f('ix_maintenance_logs_maintenance_type'), table_name='maintenance_logs')
    op.drop_index(op.f('ix_maintenance_logs_equipment_id'), table_name='maintenance_logs')
    op.drop_index(op.f('ix_maintenance_logs_date'), table_name='maintenance_logs')
    op.drop_table('maintenance_logs')
    op.drop_index(op.f('ix_equipment_type'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_skater_id'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_is_active'), table_name='equipment')
    op.drop_table('equipment')
    op.drop_table('test_levels')
    op.drop_table('competitive_levels')
    op.drop_index(op.f('ix_adult_age_classes_code'), table_name='adult_age_classes')
    op.drop_table('adult_age_classes')
    # ### end Alembic commands ###
