"""sprint4_gap_assessments

Revision ID: d16d693ecf4a
Revises: c1f2d3e4b5a6
Create Date: 2026-09-04 14:28:59.016139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd16d693ecf4a'
down_revision: Union[str, Sequence[str], None] = 'c1f2d3e4b5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gap_assessments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('skater_id', sa.Integer(), nullable=False),
    sa.Column('benchmark_framework', sa.String(length=150), nullable=False),
    sa.Column('pillar_scores', sa.JSON(), nullable=False),
    sa.Column('coach_notes', sa.Text(), nullable=True),
    sa.Column('evaluation_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['skater_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gap_assessments_skater_id'), 'gap_assessments', ['skater_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gap_assessments_skater_id'), table_name='gap_assessments')
    op.drop_table('gap_assessments')
    # ### end Alembic commands ###
