"""sprint5_injuries_meetings_standards

Revision ID: d2fe11906217
Revises: 826799aa7ee1
Create Date: 2026-09-03 20:24:24.189114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2fe11906217'
down_revision: Union[str, Sequence[str], None] = '826799aa7ee1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coach_meetings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('skater_id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('meeting_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('content_overview', sa.Text(), nullable=True),
    sa.Column('meeting_notes', sa.Text(), nullable=True),
    sa.Column('action_items', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skater_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coach_meetings_coach_id'), 'coach_meetings', ['coach_id'], unique=False)
    op.create_index(op.f('ix_coach_meetings_skater_id'), 'coach_meetings', ['skater_id'], unique=False)
    op.create_table('development_standards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('framework_type', sa.String(length=50), nullable=True),
    sa.Column('coach_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('injury_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('skater_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('body_part', sa.String(length=100), nullable=True),
    sa.Column('onset_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('restrictions', sa.Text(), nullable=True),
    sa.Column('clearance_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['skater_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_injury_records_skater_id'), 'injury_records', ['skater_id'], unique=False)
    op.create_table('standard_benchmarks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('standard_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('pillar', sa.String(length=30), nullable=False),
    sa.Column('evaluation_mode', sa.String(length=20), nullable=False),
    sa.Column('target_metric_code', sa.String(length=60), nullable=True),
    sa.Column('target_value', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('rubric_criteria', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['standard_id'], ['development_standards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_standard_benchmarks_standard_id'), 'standard_benchmarks', ['standard_id'], unique=False)
    op.create_table('skater_benchmark_assessments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('skater_id', sa.Integer(), nullable=False),
    sa.Column('benchmark_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('assessment_notes', sa.Text(), nullable=True),
    sa.Column('assessed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['benchmark_id'], ['standard_benchmarks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skater_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skater_benchmark_assessments_benchmark_id'), 'skater_benchmark_assessments', ['benchmark_id'], unique=False)
    op.create_index(op.f('ix_skater_benchmark_assessments_skater_id'), 'skater_benchmark_assessments', ['skater_id'], unique=False)
    op.add_column('skater_profiles', sa.Column('target_standard_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'skater_profiles', 'development_standards', ['target_standard_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'skater_profiles', type_='foreignkey')
    op.drop_column('skater_profiles', 'target_standard_id')
    op.drop_index(op.f('ix_skater_benchmark_assessments_skater_id'), table_name='skater_benchmark_assessments')
    op.drop_index(op.f('ix_skater_benchmark_assessments_benchmark_id'), table_name='skater_benchmark_assessments')
    op.drop_table('skater_benchmark_assessments')
    op.drop_index(op.f('ix_standard_benchmarks_standard_id'), table_name='standard_benchmarks')
    op.drop_table('standard_benchmarks')
    op.drop_index(op.f('ix_injury_records_skater_id'), table_name='injury_records')
    op.drop_table('injury_records')
    op.drop_table('development_standards')
    op.drop_index(op.f('ix_coach_meetings_skater_id'), table_name='coach_meetings')
    op.drop_index(op.f('ix_coach_meetings_coach_id'), table_name='coach_meetings')
    op.drop_table('coach_meetings')
    # ### end Alembic commands ###
