"""sprint2 programs and program_elements

Revision ID: fe7c0b098573
Revises: 636748e0b2b6
Create Date: 2026-09-03 19:22:26.437266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe7c0b098573'
down_revision: Union[str, Sequence[str], None] = '636748e0b2b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('skater_id', sa.Integer(), nullable=False),
    sa.Column('program_type', sa.String(length=4), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('season', sa.String(length=20), nullable=True),
    sa.Column('music_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('segment_bonus', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['skater_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programs_skater_id'), 'programs', ['skater_id'], unique=False)
    op.create_table('program_elements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('program_id', sa.Uuid(), nullable=False),
    sa.Column('segment_order', sa.Integer(), nullable=False),
    sa.Column('element_code', sa.String(length=50), nullable=False),
    sa.Column('is_second_half_bonus', sa.Boolean(), nullable=False),
    sa.Column('element_bonus', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('transition_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_elements_program_id'), 'program_elements', ['program_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_program_elements_program_id'), table_name='program_elements')
    op.drop_table('program_elements')
    op.drop_index(op.f('ix_programs_skater_id'), table_name='programs')
    op.drop_table('programs')
    # ### end Alembic commands ###
